services:
  app:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: SWStarter_app
    working_dir: /var/www/html
    env_file:
      - .env
    ports:
      - "8011:8011"
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: SWStarter_redis
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  scheduler:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: SWStarter_scheduler
    working_dir: /var/www/html
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
      - app
    command: >
       sh -c "
       while true; do
         php artisan schedule:run --no-interaction || true;
         sleep 60;
       done
       "

  queue:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: SWStarter_queue
    working_dir: /var/www/html
    env_file:
      - .env
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
      - app
    command: >
       sh -c "php artisan queue:work || true;"

volumes:
  redis_data:
